version: '3.3'

services:
  app:
    image: 192.168.33.10:8082/repository/docker-images/app:${APP_VERSION}
    container_name: app
    ports:
      - "8089:8089"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=cantine
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    networks:
      - nexus-network

  mysql:
    image: mysql:8.0.32
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cantine
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    networks:
      - nexus-network

networks:
  nexus-network:

volumes:
  mysql_data:
